[package]
name = "model"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
lsm-tree = { path="..", features = ["lz4"] }
mimalloc = "0.1.48"
rand = "0.9.2"
tempfile = "3.23.0"
